env:
    browser: true
    es6: true
extends: 'eslint:recommended'
rules:
    detect-non-literal-regexp:
        - off
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - double
    semi:
        - error
        - always
    eqeqeq:
        - error
        - always
    camelcase:
        - error
    no-trailing-spaces:
        - error
    curly:
        - off
    arrow-parens:
        - off